# A workflow to build a docker image and pushes to container registry (AWS ECR)

name: Docker build and push

on:
  workflow_call:
    inputs:
      artifacts_name:
        required: true
        type: string
        description: "Key to artifacts cache to download build artifacts"
      remove_artifacts:
        required: false
        type: boolean
        default: true
        description: "true | false - if true, removes the cached artifacts"
      repository_name:
        required: true
        type: string
        description: "Name of the repository for the docker image"
      image_tag:
        required: true
        type: string
        description: "Image tag"
      build_arguments:
        required: false
        type: string
        default: ''
        description: "Docker build arguments such as '--build-arg=X=Y --build-arg=A=B'"
      aws_region:
        required: true
        type: string
        description: "AWS region such as us-east-1"
    secrets:
      aws_access_key_id:
        required: true
        description: "AWS IAM user's access key ID"
      aws_secret_access_key:
        required: true
        description: "AWS IAM user's secret access key"

jobs:
  build_push_image:
    name: Build and push image to AWS ECR
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.artifacts_name }}
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.aws_access_key_id }}
          aws-secret-access-key: ${{ secrets.aws_secret_access_key }}
          aws-region: ${{ inputs.aws_region }}
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - name: Build, tag, and push image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ inputs.repository_name }}
          IMAGE_TAG: ${{ inputs.image_tag }}
          BRANCH_TAG: ${{ github.ref_name }}
        run: |
          docker build ${{ inputs.build_arguments }} -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG -t $ECR_REGISTRY/$ECR_REPOSITORY:$BRANCH_TAG .
          docker push --all-tags $ECR_REGISTRY/$ECR_REPOSITORY
          echo "Pushed image with tags" $IMAGE_TAG "and" $BRANCH_TAG
      - name: Remove artifacts (optional)
        if: ${{ inputs.remove_artifacts }}
        uses: geekyeggo/delete-artifact@v1
        with:
          name: ${{ inputs.artifacts_name }}
      - name: Notify on Slack
        uses: slackapi/slack-github-action@v1.19.0
        with:
          channel-id: 'C03EN50UX0C'
          slack-message: "GitHub build result: ${{ job.status }}\nPushed ${{ inputs.image_tag }} to ${{ inputs.repository_name }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}"
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}