
name: Called test workflow

on:
  workflow_call:
    inputs:
      artifacts:
        required: true
        type: string
    secrets:
      aws_access_key_id:
        required: true

jobs:
  print_stuff:
    name: Printing context and inputs
    runs-on: ubuntu-latest
    steps:
      - name: List current folder and files
        run: |
          echo "Listing directories..."
          echo $(pwd)
          echo $(ls -l)
      - name: Print inputs and secrets
        run: echo "input path =" ${{ inputs.artifacts }} "secrets =" ${{ secrets.aws_access_key_id }}
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.artifacts }}
      - name: Check workspace after download
        run: |
          echo "Checing out the workspace..."
          echo $(pwd)
          echo $(ls)
          echo "Listing one level higher..."
          echo $(ls ..)
      - name: Delete artifact
        uses: geekyeggo/delete-artifact@v1
        with:
          name: ${{ inputs.artifacts }}
      - name: Pring github context vars
        run: |
          echo "github.repository =" ${{ github.repository }}
          echo "github.ref =" ${{ github.ref }}
          echo "github.workspace =" ${{ github.workspace }}