# Deploy service to a Kubernetes namespace using Helm (v3) charts

name: Deploy to a Kubernetes namespace using Helm 3

on:
  workflow_call:
    inputs:
      release_name:
        required: true
        type: string
        description: "Release name used in a Helm chart"
      values_files:
        required: true
        type: string
        description: "Array of values files, e.g. [../logi-fleet/values-test.yaml', './values-test' ]"
      image_tag:
        required: true
        type: string
        description: "Image tag to override that in the values file"
      namespace:
        required: true
        type: string
        description: "Namespace to deploy to"
      kube_context:
        required: true
        type: string
        description: "The kubernetes context/cluster where the namespace is available"
      kube_config:
        required: true
        type: string
        description: "The kubeconig file with credentials to access the Kubernetes cluster and run helm/kubeconfig"


jobs:
  deployment:
    name: Deploy service
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@v3'
        with:
          repository: logistimo/fleet-deployments
      - name: 'Deploy'
        uses: 'deliverybot/helm@master'
        with:
          token: '${{ github.token }}'
          chart: './${{ inputs.release_name }}'
          secrets: '${{ toJSON(secrets) }}'
          kube-context: ${{ inputs.kube_context }}
          namespace: ${{ inputs.namespace }}
          release: ${{ inputs.release_name }}
          value-files: ${{ inputs.values_files }}
          values: |
            deployment:
              image:
                tag: ${{ inputs.image_tag }}
          helm: helm3
        env:
          KUBECONFIG_FILE: '${{ inputs.kube_config }}'
