# A workflow to build a docker image and push to container registry (AWS ECR)

name: Docker build and push

on:
  workflow_call:
    inputs:
      artifacts_name:
        required: true
        type: string
      repository_name:
        required: true
        type: string
      image_tag:
        required: true
        type: string
      aws_region:
        required: true
        type: string
    secrets:
      aws_access_key_id:
        required: true
      aws_secret_access_key:
        required: true

  build_push_image:
    name: Build and push image to AWS ECR
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.artifacts_name }}
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.aws_access_key_id }}
          aws-secret-access-key: ${{ secrets.aws_secret_access_key }}
          aws-region: ${{ inputs.aws_region }}
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - name: Build, tag, and push image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ inputs.repository_name }}
          IMAGE_TAG: ${{ inputs.image_tag }}
          BRANCH_TAG: ${{ github.ref_name }}
        run: |
          echo "ECR_REGISTRY =" $ECR_REGISTRY "ECR_REPOSITORY =" $ECR_REPOSITORY "IMAGE_TAG = " $IMAGE_TAG "BRANCH_TAG = " $BRANCH_TAG
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG -t $ECR_REGISTRY/$ECR_REPOSITORY:$BRANCH_TAG .
          docker push --all-tags $ECR_REGISTRY/$ECR_REPOSITORY
          echo "Pushed image with tags" $IMAGE_TAG "and" $BRANCH_TAG