# This workflow will build a Java project with Maven and scan code. It requires that the repo has the files:
#  buildscripts/build.sh and buildscripts/scan.sh
# The
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  workflow_call:
    inputs:
      store_artifacts:
        required: true
        type: string
      artifacts_name:
        required: false
        type: string
    secrets:
      packages_user:
        required: true
      packages_access_token:
        required: true
      sonar_access_token:
        required: true
    outputs:
      app_version:
        description: "App. version"
        value: ${{ jobs.install_packages.outputs.app_version }}
      short_commit_sha:
        description: "Short commit SHA"
        value: ${{ jobs.install_packages.outputs.short_commit_sha }}

jobs:
  install_packages:
    name: Build, scan and test (optional)
    runs-on: ubuntu-latest
    outputs:
      app_version: ${{ steps.vars.outputs.app_version }}
      short_commit_sha: ${{ steps.vars.outputs.short_commit_sha }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'temurin'
          cache: 'maven'
      - name: Get build variables
        id: vars
        run: |
          echo "::set-output name=app_version::$(buildscripts/getversion.sh)"
          echo "::set-output name=short_commit_sha::$(git rev-parse --short HEAD)"
      - name: Build packages
        run: buildscripts/build.sh install ${{ secrets.packages_user }} ${{ secrets.packages_access_token }}
      - name: Scan code
        run: buildscripts/scan.sh ${{ steps.vars.outputs.app_version }} ${{ steps.vars.outputs.short_commit_sha }} ${{ secrets.sonar_access_token }}
      - name: Copy artifacts (optional)
        if: ${{ inputs.store_artifacts == 'true' }}
        run: buildscripts/copyartifacts.sh __artifacts
      - name: Upload artifacts (optional)
        if: ${{ inputs.store_artifacts == 'true' }}
        uses: actions/upload-artifact@v3
        with:
          name: ${{ inputs.artifacts_name }}
          path: __artifacts
          retention-days: 1