# This workflow will publish a package to an artifact repository (Github Packages) using buildscripts


name: Publish packages to artifact repository

on:
  workflow_call:
    inputs:
      build_type:
        required: true
        type: string
        description: "The type of build - maven | node"
      working_directory:
        required: false
        type: string
        default: "."
        description: "Working directory for the run steps"
    secrets:
      packages_user:
        required: true
        description: "Github packages user"
      packages_access_token:
        required: true
        description: "Gihub packages access token"

jobs:
  install_packages:
    name: Publish packages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up JDK 8
        if: ${{ inputs.build_type == 'maven' }}
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'temurin'
          cache: 'maven'
      - uses: actions/setup-node@v2
        if: ${{ inputs.build_type == 'node' }}
        with:
          node-version: '14'
          cache: 'npm'
      - name: Deploy packages
        working-directory: ${{ inputs.working_directory }}
        run: buildscripts/build.sh deploy ${{ secrets.packages_user }} ${{ secrets.packages_access_token }}